# Generated by Django 4.0 on 2025-04-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teams',
            new_name='team',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
